"use client";

import type {ReactNode,RefObject} from "react";
import { useCloud } from "./cloud-provider";
import { DojoPageHeader,DojoPageFooter } from "./dojo-page-chrome";
import { AnimatedFighter } from "./animated-fighter";
import { GuestMigration } from "./account-page";
import { Progress } from "./ui/progress";
import { ProgressManager } from "./progress-manager";
import { BELT_ORDER,type CourseListing } from "@/lib/cloud-types";
import { previewScore } from "@/lib/guest-preview";
import { trainingHref } from "@/lib/course-engine";
import { principles } from "@/lib/philosophy-content";
import type {ProgressSnapshot,ProgressStore} from "@/lib/dojo-progress";

export function CloudMyDojoPage({brand,headingRef,store,snapshot:local}:{brand:ReactNode;headingRef:RefObject<HTMLHeadingElement|null>;store:ProgressStore;snapshot:ProgressSnapshot}) {
  const cloud=useCloud(),state=cloud.snapshot;
  const available=cloud.courses.filter(course=>course.availability==="available");
  const done=(course:CourseListing)=>state?.modules.filter(item=>item.course_id===course.id&&item.completed).length??0;
  const next=available.find(course=>course.access==="open"&&done(course)<course.moduleCount)??available.find(course=>done(course)<course.moduleCount)??available[0];
  const modules=available.reduce((sum,course)=>sum+course.moduleCount,0),completed=available.reduce((sum,course)=>sum+done(course),0),maxXp=available.reduce((sum,course)=>sum+course.maxXp,0);
  const previewXp=cloud.guest.submitted&&previewScore(cloud.guest)===3?20:0;
  const review=state?.modules.filter(item=>item.submitted&&!item.feedback?.passed&&item.feedback?.questions.some(q=>!q.correct))??[];
  const actionHref=next?.access==="open"?trainingHref(next.id):"#account";
  return <div className="dojo-page-shell my-dojo-shell"><DojoPageHeader brand={brand} currentPage="my-dojo"/><main id="my-dojo-content" className="my-dojo-main" tabIndex={-1}><section className="my-dojo-intro"><div><p className="eyebrow">MY DOJO / YOUR PERSONAL PATH</p><h1 ref={headingRef} tabIndex={-1}>YOUR PRACTICE.<br/>YOUR PACE.</h1><p>No streaks to chase. One useful step at a time.</p><span className="my-dojo-storage">{cloud.session?cloud.error?"CLOUD CONNECTION NEEDS ATTENTION":cloud.busy?"SYNCING YOUR ACCOUNT":"ACCOUNT PROGRESS":cloud.guestSaved?"GUEST PREVIEW / THIS BROWSER":"GUEST PREVIEW / THIS TAB"}</span></div><a className="about-text-link" href={cloud.session?"#account":"#account/signup"}>{cloud.session?"MANAGE ACCOUNT":"CREATE FREE ACCOUNT"} ➜</a></section>
    {cloud.error&&cloud.session&&<div className="feedback" role="alert"><p>{cloud.error}</p><button className="about-text-link" disabled={cloud.busy} onClick={()=>void cloud.refresh()}>RECONNECT</button></div>}
    {cloud.session?<><GuestMigration/>{!state?<p role="status">Loading your saved progress…</p>:<><div className="my-dojo-stats" aria-label="Account training progress"><article className="pixel-frame"><span>TRAINING XP</span><strong>{state.xp}<small> / {maxXp}</small></strong></article><article className="pixel-frame"><span>COURSES COMPLETE</span><strong>{available.filter(course=>done(course)===course.moduleCount).length}<small> / {available.length}</small></strong></article><article className="pixel-frame"><span>BELTS EARNED</span><strong>{state.awards.length}<small> / 8</small></strong></article><article className="pixel-frame"><span>STEPS COMPLETE</span><strong>{completed}<small> / {modules}</small></strong></article></div><section className="my-dojo-next pixel-frame"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2>{next?done(next)===next.moduleCount?"A USEFUL HABIT. KEEP IT SHARP.":next.title:"THE PATH IS TAKING SHAPE."}</h2><p>{next?next.access==="subscription"?"You earned White. Premium training opens with an active test subscription.":next.access==="prerequisite"?"Complete the earlier belt and course requirements first.":done(next)===next.moduleCount?"Your available practice is complete. Revisit a step while the full curriculum is prepared.":"Continue from your first incomplete step. Your account keeps the progress.":"Training appears here when the owner publishes it."}</p><a className="pixel-button" href={next?actionHref:"#belts"}>{next?.access==="subscription"?"OPEN PREMIUM ACCESS":next?.access==="open"?"CONTINUE TRAINING":"EXPLORE YOUR PATH"} ➜</a><div className="my-dojo-overall"><Progress value={maxXp?state.xp/maxXp*100:0} aria-label="Published training XP"/><span>{state.xp} / {maxXp} XP · Published practice</span></div></div><div className="my-dojo-guardian" aria-hidden="true"><AnimatedFighter role="training" className="my-dojo-fighter"/><span>PAUSE.<br/>VERIFY.<br/>PROTECT.</span></div></section>
      <section className="my-dojo-courses"><div className="belts-section-title"><p className="eyebrow">YOUR COURSE PATH</p><h2>ONE CLEAR NEXT STEP.</h2><p>Account access, subscription access and belt awards follow different rules.</p></div><div className="my-dojo-course-grid">{available.map(course=><article key={course.id} className="my-dojo-course pixel-frame"><div className="my-dojo-course-top"><p className="eyebrow">{course.belt.toUpperCase()} BELT</p><span className="course-status">{done(course)===course.moduleCount?"COMPLETE":course.access==="open"?done(course)?"IN PROGRESS":"READY":course.access==="subscription"?"SUBSCRIPTION NEEDED":"PREREQUISITE NEEDED"}</span></div><h3>{course.title}</h3><p>{course.summary}</p><div className="my-dojo-course-progress"><Progress value={done(course)/course.moduleCount*100} aria-label={`${course.title} completion`}/><span>{done(course)} / {course.moduleCount} steps</span></div>{course.testContent&&<p className="pilot-label">TEST MATERIAL / {course.awardsBelt?"Test belt award":"Pilot only; no full belt award"}</p>}<a className="pixel-button pixel-button-light" href={course.access==="open"?trainingHref(course.id):course.access==="subscription"?"#account":`#belts/${course.belt}`}>{course.access==="open"?"OPEN PRACTICE":"VIEW REQUIREMENTS"} ➜</a></article>)}</div></section>
      {review.length>0&&<section className="my-dojo-review pixel-frame"><p className="eyebrow">YOUR NEXT ROUND</p><h2>REVIEW AND TRY AGAIN.</h2><ul>{review.map(item=><li key={`${item.course_id}/${item.module_id}`}><a href={trainingHref(item.course_id,item.module_id)}>{cloud.courses.find(course=>course.id===item.course_id)?.title} / {item.module_id.toUpperCase()} ➜</a></li>)}</ul></section>}
      <section className="my-dojo-belts pixel-frame"><p className="eyebrow">YOUR BELT RECORD</p><h2>PROGRESS YOU EARNED.</h2><div className="belt-record">{BELT_ORDER.map(belt=><a key={belt} href={`#belts/${belt}`} className={`belt-record-item ${state.awards.some(award=>award.belt===belt)?"earned":""}`}><span className={`belt-dot belt-${belt}`}/>{belt.toUpperCase()}<small>{state.awards.some(award=>award.belt===belt)?"EARNED ✓":"NOT EARNED"}</small></a>)}</div><p className="session-note">Your record stays saved when a subscription ends. A pilot is not a full belt or certification.</p></section>
      <section className="my-dojo-habits pixel-frame"><p className="eyebrow">YOUR DOJO CODE</p><h2>SMALL HABITS. STEADY PRACTICE.</h2><div className="my-dojo-habit-grid">{principles.map(principle=><a key={principle.id} href={`#philosophy/${principle.id}`}><strong>{principle.title.toUpperCase()}</strong><span>{state.profile.habits.includes(principle.id)?"IN YOUR PRACTICE ✓":"CHOOSE YOUR PRACTICE"}</span></a>)}</div></section>
    </>}</>:<><div className="my-dojo-stats"><article className="pixel-frame"><span>PREVIEW QUESTIONS</span><strong>{Object.keys(cloud.guest.answers).length}<small> / 3</small></strong></article><article className="pixel-frame"><span>PREVIEW XP</span><strong>{previewXp}</strong></article><article className="pixel-frame"><span>WHITE ACCESS</span><strong>FREE</strong></article><article className="pixel-frame"><span>NEXT STEP</span><strong>ACCOUNT</strong></article></div><section className="my-dojo-next pixel-frame"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2>{cloud.guest.submitted?"KEEP YOUR FIRST STEP.":"TRY YOUR FIRST THREE MOVES."}</h2><p>{cloud.guest.submitted?"Create a free account to save your preview and continue the White lesson and quiz. No payment card is needed.":"Start with three questions, then make a free account to continue White."}</p><a className="pixel-button" href={cloud.guest.submitted?"#account/signup":"#dojo"}>{cloud.guest.submitted?"CREATE FREE ACCOUNT":"TRY WHITE"} ➜</a></div><div className="my-dojo-guardian" aria-hidden="true"><AnimatedFighter role="training" className="my-dojo-fighter"/><span>START.<br/>PRACTICE.<br/>GROW.</span></div></section></>}
    <section className="my-dojo-planned"><p className="eyebrow">THE BELT PATH</p><h2>WHITE FIRST. THEN KEEP GROWING.</h2><div className="my-dojo-planned-list">{BELT_ORDER.map(belt=><a key={belt} href={`#belts/${belt}`}><strong>{belt.toUpperCase()}</strong><span>{belt==="white"?"FREE ACCOUNT":cloud.courses.some(course=>course.belt===belt&&course.availability==="available")?"PREMIUM + PREREQUISITES":"IN DEVELOPMENT"}</span><span aria-hidden="true">➜</span></a>)}</div></section>
    {!cloud.session&&<section id="my-dojo-backups" className="my-dojo-backups pixel-frame"><p className="eyebrow">EARLIER LOCAL VERSIONS</p><h2 id="my-dojo-backups-title" tabIndex={-1}>YOUR EXISTING BACKUP.</h2><p>Your 0.4 browser profile is kept separately. A local backup cannot grant cloud XP, a belt or paid access. Preview answers are checked again when you transfer them.</p><ProgressManager store={store} snapshot={local}/></section>}
  </main><DojoPageFooter/></div>;
}
